"""added status

Revision ID: 0744a012eabc
Revises: d642b353be1d
Create Date: 2025-08-26 05:58:15.897100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0744a012eabc'
down_revision: Union[str, Sequence[str], None] = 'd642b353be1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lister_buyers', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lister_buyers', 'status')
    # ### end Alembic commands ###
