"""modified freq

Revision ID: 110d9aedfe22
Revises: 3352f320e2a0
Create Date: 2025-08-27 04:32:10.547095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110d9aedfe22'
down_revision: Union[str, Sequence[str], None] = '3352f320e2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rent_properties', 'freq',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rent_properties', 'freq',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
