"""added freq

Revision ID: 3352f320e2a0
Revises: 6e51cc237c3d
Create Date: 2025-08-27 04:28:08.486806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3352f320e2a0'
down_revision: Union[str, Sequence[str], None] = '6e51cc237c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rent_properties',
        sa.Column('freq', sa.String(), nullable=False, server_default='monthly')
    )
    # remove the server_default afterwards if you don’t want it applied to new rows
    op.alter_column('rent_properties', 'freq', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent_properties', 'freq')
    # ### end Alembic commands ###
