"""deleted fields

Revision ID: 4209865a681f
Revises: a65ea86f0309
Create Date: 2025-08-27 04:13:26.718564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4209865a681f'
down_revision: Union[str, Sequence[str], None] = 'a65ea86f0309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_properties', sa.Column('property_score', sa.Float(), nullable=True))
    op.add_column('rent_properties', sa.Column('property_score', sa.Float(), nullable=True))
    op.drop_column('users', 'property_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('property_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('rent_properties', 'property_score')
    op.drop_column('buy_properties', 'property_score')
    # ### end Alembic commands ###
