"""added new columns

Revision ID: 5d103da08456
Revises: 4b0eec7d401a
Create Date: 2025-08-25 22:10:18.732966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d103da08456'
down_revision: Union[str, Sequence[str], None] = '4b0eec7d401a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('premium_listings', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('has_free_listings', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('max_listings', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('used_listings', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('extra_points', sa.Float(), nullable=True))
    op.drop_column('users', 'boosts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('boosts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'extra_points')
    op.drop_column('users', 'used_listings')
    op.drop_column('users', 'max_listings')
    op.drop_column('users', 'has_free_listings')
    op.drop_column('users', 'premium_listings')
    # ### end Alembic commands ###
