"""added fields

Revision ID: 97f6d0fd255e
Revises: 
Create Date: 2025-08-24 20:22:08.425736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '97f6d0fd255e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_properties', sa.Column('document_list', sqlite.JSON(), nullable=True))
    op.add_column('users', sa.Column('boosts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'boosts')
    op.drop_column('buy_properties', 'document_list')
    # ### end Alembic commands ###
