"""added new fields

Revision ID: a65ea86f0309
Revises: bde50408d908
Create Date: 2025-08-27 02:27:21.626748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65ea86f0309'
down_revision: Union[str, Sequence[str], None] = 'bde50408d908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lister_buyers', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('lister_tenants', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lister_tenants', 'message')
    op.drop_column('lister_buyers', 'message')
    # ### end Alembic commands ###
