"""added something

Revision ID: a84b05baed9b
Revises: c5b244f17620
Create Date: 2025-08-26 00:42:28.753629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84b05baed9b'
down_revision: Union[str, Sequence[str], None] = 'c5b244f17620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_properties', sa.Column('listed_at', sa.DateTime(), nullable=True))
    op.add_column('lister_tenants', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lister_tenants', 'status')
    op.drop_column('buy_properties', 'listed_at')
    # ### end Alembic commands ###
