"""added new fields

Revision ID: bde50408d908
Revises: 167447474c75
Create Date: 2025-08-26 21:22:57.338814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bde50408d908'
down_revision: Union[str, Sequence[str], None] = '167447474c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_properties', sa.Column('aidesc', sqlite.JSON(), nullable=True))
    op.add_column('buy_properties', sa.Column('videos', sqlite.JSON(), nullable=True))
    op.add_column('rent_properties', sa.Column('aidesc', sqlite.JSON(), nullable=True))
    op.add_column('rent_properties', sa.Column('videos', sqlite.JSON(), nullable=True))
    op.add_column('users', sa.Column('property_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'property_score')
    op.drop_column('rent_properties', 'videos')
    op.drop_column('rent_properties', 'aidesc')
    op.drop_column('buy_properties', 'videos')
    op.drop_column('buy_properties', 'aidesc')
    # ### end Alembic commands ###
