"""added tags

Revision ID: c5b244f17620
Revises: 5d103da08456
Create Date: 2025-08-25 22:20:21.544304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c5b244f17620'
down_revision: Union[str, Sequence[str], None] = '5d103da08456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_properties', sa.Column('tags', sqlite.JSON(), nullable=True))
    op.add_column('rent_properties', sa.Column('tags', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent_properties', 'tags')
    op.drop_column('buy_properties', 'tags')
    # ### end Alembic commands ###
