"""added listed_at

Revision ID: d642b353be1d
Revises: a84b05baed9b
Create Date: 2025-08-26 05:00:00.334239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd642b353be1d'
down_revision: Union[str, Sequence[str], None] = 'a84b05baed9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent_properties', sa.Column('listed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent_properties', 'listed_at')
    # ### end Alembic commands ###
